name: 'Acción de repetioción'
author: 'Sergio Belda Revert'
description: 'Repite el número de veces el texto indicado'

inputs:
  input_text:
      description: 'El texto que queremos repetir varias veces'
      required: true
    num_of_repeats:
      description: 'Número de veces que queremos que aparezca el texto'
      required: false
      default: '1'

output:
  output_text:
    description: 'El texto repetido del número de veces indicado'

  #Aqui van los valores especificos paara configurar Docker
  #o JavaScript, se explicarán más adelante.

  branding: 
    icon: 'rotate-cw'
    color: 'blue'
    