--- 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      ? "-name"
      : "Build with Maven"
      ? "-uses"
      : actions/setup-java@v1
      run: "mvn -B package --file pom.xml"
      with: 
        java-version: 1.8
name: "Build and test of Java Project"
true: 
  - push